#!/bin/bash
set -e

echo "🚀 Express Entry Deployment Guide"
echo "=================================="
echo ""
echo "You have 3 options:"
echo ""
echo "Option 1: RENDER.COM (Recommended - Easiest)"
echo "  1. Go to: https://render.com"
echo "  2. Sign up with GitHub/GitLab"
echo "  3. Click 'New +' → 'BluePrint'"
echo "  4. Import this repository"
echo "  5. It will auto-detect render.yaml and deploy!"
echo ""
echo "  Expected URLs:"
echo "  - Backend: https://express-entry-backend.onrender.com"
echo "  - Frontend: https://express-entry-frontend.onrender.com"
echo ""

echo "Option 2: RAILWAY.APP (Already Started!)"
echo "  Your project is already deploying on Railway."
echo "  Check: https://railway.app"
echo "  View the build logs in the dashboard"
echo ""

echo "Option 3: VERCEL + RAILWAY (Best for Frontend/Backend Split)"
echo "  Frontend on Vercel:"
echo "    npm install -g vercel"
echo "    cd frontend && vercel deploy"
echo ""
echo "  Backend stays on Railway (already deploying)"
echo ""

echo "=================================="
echo "✅ NEXT STEPS:"
echo "=================================="
echo ""
echo "For RENDER (Easiest):"
echo "  1. Push code to GitHub/GitLab (if not already)"
echo "  2. Go to https://render.com"
echo "  3. Connect your GitHub/GitLab account"
echo "  4. Create New → BluePrint"
echo "  5. Select your express_entry repository"
echo "  6. It will auto-detect services from render.yaml"
echo "  7. Click 'Deploy'"
echo "  8. Wait 5-10 minutes ☕"
echo ""
echo "For RAILWAY (Already Running):"
echo "  1. Go to: https://railway.app"
echo "  2. Check your 'Express Entry' project"
echo "  3. View build logs"
echo "  4. Once ready, get your service URLs from the dashboard"
echo ""
echo "=================================="
