#!/bin/bash

echo "🚀 Setting up Railway with PostgreSQL Database"
echo "=============================================="
echo ""
echo "STEP 1: Go to your Railway Dashboard"
echo "  👉 https://railway.com/project/57b1b937-ce99-4533-a4a7-4281f0108dbf"
echo ""
echo "STEP 2: Click on your BACKEND service (Express Entry)"
echo ""
echo "STEP 3: Go to the 'Variables' tab"
echo ""
echo "STEP 4: Add the following environment variables:"
echo "=============================================="
echo ""
echo "Variable 1:"
echo "  Key:   DATABASE_URL"
echo "  Value: postgresql://postgres:DyZgkucnXCSnaBedWcSXxvOytyloLfHY@postgres.railway.internal:5432/railway"
echo ""
echo "Variable 2:"
echo "  Key:   APP_ENV"
echo "  Value: production"
echo ""
echo "Variable 3:"
echo "  Key:   DEBUG"
echo "  Value: false"
echo ""
echo "=============================================="
echo ""
echo "STEP 5: Once you've added all variables, click 'Redeploy'"
echo ""
echo "STEP 6: Wait 3-5 minutes for the build and deployment"
echo ""
echo "STEP 7: Check the logs to confirm it connected to the database"
echo ""
echo "Expected log message:"
echo "  ✓ Database tables initialised"
echo ""
echo "=============================================="
echo ""
echo "Questions?"
echo "  1. If you see 'Skipping DB init' - DATABASE_URL wasn't set"
echo "  2. If you see connection timeout - check the URL format"
echo "  3. If deployment fails - check the build logs"
echo ""
